// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
// A namespace for generated variants and helper functions.
export namespace EntityState {
  // These are the generated variant types for each variant of the tagged union.
  // One type is generated per variant and will be used in the `value` field of
  // the tagged union.
  export type Idle = { tag: "Idle" };
  export type Moving = { tag: "Moving" };
  export type Throwing = { tag: "Throwing" };
  export type Catching = { tag: "Catching" };
  export type Holding = { tag: "Holding" };
  export type Hit = { tag: "Hit" };
  export type Lost = { tag: "Lost" };
  export type Won = { tag: "Won" };

  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  export const Idle = { tag: "Idle" };
  export const Moving = { tag: "Moving" };
  export const Throwing = { tag: "Throwing" };
  export const Catching = { tag: "Catching" };
  export const Holding = { tag: "Holding" };
  export const Hit = { tag: "Hit" };
  export const Lost = { tag: "Lost" };
  export const Won = { tag: "Won" };

  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createSumType([
      new SumTypeVariant("Idle", AlgebraicType.createProductType([])),
      new SumTypeVariant("Moving", AlgebraicType.createProductType([])),
      new SumTypeVariant("Throwing", AlgebraicType.createProductType([])),
      new SumTypeVariant("Catching", AlgebraicType.createProductType([])),
      new SumTypeVariant("Holding", AlgebraicType.createProductType([])),
      new SumTypeVariant("Hit", AlgebraicType.createProductType([])),
      new SumTypeVariant("Lost", AlgebraicType.createProductType([])),
      new SumTypeVariant("Won", AlgebraicType.createProductType([])),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: EntityState): void {
      EntityState.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): EntityState {
      return EntityState.getTypeScriptAlgebraicType().deserialize(reader);
  }

}

// The tagged union or sum type for the algebraic type `EntityState`.
export type EntityState = EntityState.Idle | EntityState.Moving | EntityState.Throwing | EntityState.Catching | EntityState.Holding | EntityState.Hit | EntityState.Lost | EntityState.Won;

export default EntityState;

